spring:
  application:
    name: person-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/climate
    username: climateadm
    password: obiwan
  jpa:
    hibernate:
      ddl-auto: validate
